# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Timetracker User Interface CI

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:
    branches: [master]

jobs:
  build_production:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v20]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            nobio/timetracker-ui
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      - name: Install angular
        run: npm i -D -E @angular/cli

 #     - name: Use coturiv/setup-ionic
 #       uses: coturiv/setup-ionic@v1

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Build App
        # run: ionic build -c k8s
        # run: ionic build -c docker
        run: ionic build -c production

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}.prod

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  build_k8s:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v20]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            nobio/timetracker-ui
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr

      - name: Install angular
        run: npm i -D -E @angular/cli

      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1

      - name: Build App
        run: ionic build -c k8s
        # run: ionic build -c docker
        # run: ionic build -c production

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}.k8s

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
